#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="News")]
	public partial class NewsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertPost1(Post1 instance);
    partial void UpdatePost1(Post1 instance);
    partial void DeletePost1(Post1 instance);
    #endregion
		
		public NewsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NewsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Post1> Post1s
		{
			get
			{
				return this.GetTable<Post1>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Cat_Delete")]
		public int Cat_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_cat", DbType="Int")] System.Nullable<int> iD_cat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_cat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.User_Update")]
		public int User_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_name", DbType="NChar(50)")] string user_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_pass", DbType="NChar(50)")] string user_pass, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_user", DbType="Int")] System.Nullable<int> iD_user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_name, user_pass, iD_user);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Cat_Insert")]
		public int Cat_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cat_name", DbType="NVarChar(50)")] string cat_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cat_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Cat_SelectAll")]
		public ISingleResult<Cat_SelectAllResult> Cat_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Cat_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Cat_SelectID")]
		public ISingleResult<Cat_SelectIDResult> Cat_SelectID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCat);
			return ((ISingleResult<Cat_SelectIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Cat_Update")]
		public int Cat_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cat_name", DbType="NVarChar(50)")] string cat_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_cat", DbType="Int")] System.Nullable<int> iD_cat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cat_name, iD_cat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_SelectAll")]
		public ISingleResult<Post_SelectAllResult> Post_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Post_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_SelectHome")]
		public ISingleResult<Post_SelectHomeResult> Post_SelectHome([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_cat", DbType="Int")] System.Nullable<int> iD_cat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_cat);
			return ((ISingleResult<Post_SelectHomeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_SelectIDcat")]
		public ISingleResult<Post_SelectIDcatResult> Post_SelectIDcat([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_cat", DbType="Int")] System.Nullable<int> iD_cat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_cat);
			return ((ISingleResult<Post_SelectIDcatResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_SelectRandom")]
		public ISingleResult<Post_SelectRandomResult> Post_SelectRandom([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCat);
			return ((ISingleResult<Post_SelectRandomResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_slide")]
		public ISingleResult<Post_slideResult> Post_slide()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Post_slideResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_Update")]
		public int Post_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_post", DbType="Int")] System.Nullable<int> iD_post, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Post_title", DbType="NVarChar(200)")] string post_title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Post_content", DbType="NVarChar(MAX)")] string post_content)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_post, post_title, post_content);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.User_Delete")]
		public int User_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_user", DbType="Int")] System.Nullable<int> iD_user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_user);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.User_Insert")]
		public int User_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_name", DbType="NChar(50)")] string user_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_pass", DbType="NChar(50)")] string user_pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_name, user_pass);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.User_Search")]
		public ISingleResult<User_SearchResult> User_Search([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_name", DbType="NChar(50)")] string user_name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_pass", DbType="NChar(50)")] string user_pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_name, user_pass);
			return ((ISingleResult<User_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.User_SelectAll")]
		public ISingleResult<User_SelectAllResult> User_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<User_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_Insert")]
		public int Post_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Post_title", DbType="NVarChar(200)")] string post_title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Post_content", DbType="NVarChar(MAX)")] string post_content, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Post_date", DbType="DateTime")] System.Nullable<System.DateTime> post_date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Post_cat", DbType="Int")] System.Nullable<int> post_cat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Post_thumb", DbType="NVarChar(100)")] string post_thumb)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), post_title, post_content, post_date, post_cat, post_thumb);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_SelectAdmin")]
		public ISingleResult<Post_SelectAdminResult> Post_SelectAdmin()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Post_SelectAdminResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_SelectID")]
		public ISingleResult<Post_SelectIDResult> Post_SelectID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_post", DbType="Int")] System.Nullable<int> iD_post)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_post);
			return ((ISingleResult<Post_SelectIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_Delete")]
		public int Post_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDpost", DbType="Int")] System.Nullable<int> iDpost)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDpost);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categories")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_cat;
		
		private string _Cat_name;
		
		private EntitySet<Post1> _Post1s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_catChanging(int value);
    partial void OnID_catChanged();
    partial void OnCat_nameChanging(string value);
    partial void OnCat_nameChanged();
    #endregion
		
		public Category()
		{
			this._Post1s = new EntitySet<Post1>(new Action<Post1>(this.attach_Post1s), new Action<Post1>(this.detach_Post1s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this.OnID_catChanging(value);
					this.SendPropertyChanging();
					this._ID_cat = value;
					this.SendPropertyChanged("ID_cat");
					this.OnID_catChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Cat_name
		{
			get
			{
				return this._Cat_name;
			}
			set
			{
				if ((this._Cat_name != value))
				{
					this.OnCat_nameChanging(value);
					this.SendPropertyChanging();
					this._Cat_name = value;
					this.SendPropertyChanged("Cat_name");
					this.OnCat_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Post1", Storage="_Post1s", ThisKey="ID_cat", OtherKey="ID_cat")]
		public EntitySet<Post1> Post1s
		{
			get
			{
				return this._Post1s;
			}
			set
			{
				this._Post1s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Post1s(Post1 entity)
		{
			this.SendPropertyChanging();
			entity.Category = this;
		}
		
		private void detach_Post1s(Post1 entity)
		{
			this.SendPropertyChanging();
			entity.Category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_user;
		
		private string _User_name;
		
		private string _User_pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_userChanging(int value);
    partial void OnID_userChanged();
    partial void OnUser_nameChanging(string value);
    partial void OnUser_nameChanged();
    partial void OnUser_passChanging(string value);
    partial void OnUser_passChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string User_name
		{
			get
			{
				return this._User_name;
			}
			set
			{
				if ((this._User_name != value))
				{
					this.OnUser_nameChanging(value);
					this.SendPropertyChanging();
					this._User_name = value;
					this.SendPropertyChanged("User_name");
					this.OnUser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_pass", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string User_pass
		{
			get
			{
				return this._User_pass;
			}
			set
			{
				if ((this._User_pass != value))
				{
					this.OnUser_passChanging(value);
					this.SendPropertyChanging();
					this._User_pass = value;
					this.SendPropertyChanged("User_pass");
					this.OnUser_passChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Posts")]
	public partial class Post1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_post;
		
		private string _Post_title;
		
		private string _Post_content;
		
		private System.Nullable<System.DateTime> _Post_date;
		
		private System.Nullable<int> _ID_cat;
		
		private string _Post_thumb;
		
		private EntityRef<Category> _Category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_postChanging(int value);
    partial void OnID_postChanged();
    partial void OnPost_titleChanging(string value);
    partial void OnPost_titleChanged();
    partial void OnPost_contentChanging(string value);
    partial void OnPost_contentChanged();
    partial void OnPost_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnPost_dateChanged();
    partial void OnID_catChanging(System.Nullable<int> value);
    partial void OnID_catChanged();
    partial void OnPost_thumbChanging(string value);
    partial void OnPost_thumbChanged();
    #endregion
		
		public Post1()
		{
			this._Category = default(EntityRef<Category>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_post", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_post
		{
			get
			{
				return this._ID_post;
			}
			set
			{
				if ((this._ID_post != value))
				{
					this.OnID_postChanging(value);
					this.SendPropertyChanging();
					this._ID_post = value;
					this.SendPropertyChanged("ID_post");
					this.OnID_postChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_title", DbType="NVarChar(200)")]
		public string Post_title
		{
			get
			{
				return this._Post_title;
			}
			set
			{
				if ((this._Post_title != value))
				{
					this.OnPost_titleChanging(value);
					this.SendPropertyChanging();
					this._Post_title = value;
					this.SendPropertyChanged("Post_title");
					this.OnPost_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_content", DbType="NVarChar(MAX)")]
		public string Post_content
		{
			get
			{
				return this._Post_content;
			}
			set
			{
				if ((this._Post_content != value))
				{
					this.OnPost_contentChanging(value);
					this.SendPropertyChanging();
					this._Post_content = value;
					this.SendPropertyChanged("Post_content");
					this.OnPost_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Post_date
		{
			get
			{
				return this._Post_date;
			}
			set
			{
				if ((this._Post_date != value))
				{
					this.OnPost_dateChanging(value);
					this.SendPropertyChanging();
					this._Post_date = value;
					this.SendPropertyChanged("Post_date");
					this.OnPost_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int")]
		public System.Nullable<int> ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					if (this._Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_catChanging(value);
					this.SendPropertyChanging();
					this._ID_cat = value;
					this.SendPropertyChanged("ID_cat");
					this.OnID_catChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_thumb", DbType="NVarChar(100)")]
		public string Post_thumb
		{
			get
			{
				return this._Post_thumb;
			}
			set
			{
				if ((this._Post_thumb != value))
				{
					this.OnPost_thumbChanging(value);
					this.SendPropertyChanging();
					this._Post_thumb = value;
					this.SendPropertyChanged("Post_thumb");
					this.OnPost_thumbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Post1", Storage="_Category", ThisKey="ID_cat", OtherKey="ID_cat", IsForeignKey=true)]
		public Category Category
		{
			get
			{
				return this._Category.Entity;
			}
			set
			{
				Category previousValue = this._Category.Entity;
				if (((previousValue != value) 
							|| (this._Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Category.Entity = null;
						previousValue.Post1s.Remove(this);
					}
					this._Category.Entity = value;
					if ((value != null))
					{
						value.Post1s.Add(this);
						this._ID_cat = value.ID_cat;
					}
					else
					{
						this._ID_cat = default(Nullable<int>);
					}
					this.SendPropertyChanged("Category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Cat_SelectAllResult
	{
		
		private int _ID_cat;
		
		private string _Cat_name;
		
		public Cat_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int NOT NULL")]
		public int ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this._ID_cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Cat_name
		{
			get
			{
				return this._Cat_name;
			}
			set
			{
				if ((this._Cat_name != value))
				{
					this._Cat_name = value;
				}
			}
		}
	}
	
	public partial class Cat_SelectIDResult
	{
		
		private int _ID_cat;
		
		private string _Cat_name;
		
		public Cat_SelectIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int NOT NULL")]
		public int ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this._ID_cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Cat_name
		{
			get
			{
				return this._Cat_name;
			}
			set
			{
				if ((this._Cat_name != value))
				{
					this._Cat_name = value;
				}
			}
		}
	}
	
	public partial class Post_SelectAllResult
	{
		
		private int _ID_post;
		
		private string _Post_title;
		
		private string _Post_content;
		
		private System.Nullable<System.DateTime> _Post_date;
		
		private System.Nullable<int> _ID_cat;
		
		private string _Post_thumb;
		
		public Post_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_post", DbType="Int NOT NULL")]
		public int ID_post
		{
			get
			{
				return this._ID_post;
			}
			set
			{
				if ((this._ID_post != value))
				{
					this._ID_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_title", DbType="NVarChar(200)")]
		public string Post_title
		{
			get
			{
				return this._Post_title;
			}
			set
			{
				if ((this._Post_title != value))
				{
					this._Post_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_content", DbType="NVarChar(MAX)")]
		public string Post_content
		{
			get
			{
				return this._Post_content;
			}
			set
			{
				if ((this._Post_content != value))
				{
					this._Post_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Post_date
		{
			get
			{
				return this._Post_date;
			}
			set
			{
				if ((this._Post_date != value))
				{
					this._Post_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int")]
		public System.Nullable<int> ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this._ID_cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_thumb", DbType="NVarChar(100)")]
		public string Post_thumb
		{
			get
			{
				return this._Post_thumb;
			}
			set
			{
				if ((this._Post_thumb != value))
				{
					this._Post_thumb = value;
				}
			}
		}
	}
	
	public partial class Post_SelectHomeResult
	{
		
		private int _ID_post;
		
		private string _Post_title;
		
		private string _Post_content;
		
		private System.Nullable<System.DateTime> _Post_date;
		
		private System.Nullable<int> _ID_cat;
		
		private string _Post_thumb;
		
		private int _ID_cat1;
		
		private string _Cat_name;
		
		public Post_SelectHomeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_post", DbType="Int NOT NULL")]
		public int ID_post
		{
			get
			{
				return this._ID_post;
			}
			set
			{
				if ((this._ID_post != value))
				{
					this._ID_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_title", DbType="NVarChar(200)")]
		public string Post_title
		{
			get
			{
				return this._Post_title;
			}
			set
			{
				if ((this._Post_title != value))
				{
					this._Post_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_content", DbType="NVarChar(MAX)")]
		public string Post_content
		{
			get
			{
				return this._Post_content;
			}
			set
			{
				if ((this._Post_content != value))
				{
					this._Post_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Post_date
		{
			get
			{
				return this._Post_date;
			}
			set
			{
				if ((this._Post_date != value))
				{
					this._Post_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int")]
		public System.Nullable<int> ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this._ID_cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_thumb", DbType="NVarChar(100)")]
		public string Post_thumb
		{
			get
			{
				return this._Post_thumb;
			}
			set
			{
				if ((this._Post_thumb != value))
				{
					this._Post_thumb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat1", DbType="Int NOT NULL")]
		public int ID_cat1
		{
			get
			{
				return this._ID_cat1;
			}
			set
			{
				if ((this._ID_cat1 != value))
				{
					this._ID_cat1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Cat_name
		{
			get
			{
				return this._Cat_name;
			}
			set
			{
				if ((this._Cat_name != value))
				{
					this._Cat_name = value;
				}
			}
		}
	}
	
	public partial class Post_SelectIDcatResult
	{
		
		private int _ID_post;
		
		private string _Post_title;
		
		private string _Post_content;
		
		private System.Nullable<System.DateTime> _Post_date;
		
		private System.Nullable<int> _ID_cat;
		
		private string _Post_thumb;
		
		public Post_SelectIDcatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_post", DbType="Int NOT NULL")]
		public int ID_post
		{
			get
			{
				return this._ID_post;
			}
			set
			{
				if ((this._ID_post != value))
				{
					this._ID_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_title", DbType="NVarChar(200)")]
		public string Post_title
		{
			get
			{
				return this._Post_title;
			}
			set
			{
				if ((this._Post_title != value))
				{
					this._Post_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_content", DbType="NVarChar(MAX)")]
		public string Post_content
		{
			get
			{
				return this._Post_content;
			}
			set
			{
				if ((this._Post_content != value))
				{
					this._Post_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Post_date
		{
			get
			{
				return this._Post_date;
			}
			set
			{
				if ((this._Post_date != value))
				{
					this._Post_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int")]
		public System.Nullable<int> ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this._ID_cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_thumb", DbType="NVarChar(100)")]
		public string Post_thumb
		{
			get
			{
				return this._Post_thumb;
			}
			set
			{
				if ((this._Post_thumb != value))
				{
					this._Post_thumb = value;
				}
			}
		}
	}
	
	public partial class Post_SelectRandomResult
	{
		
		private int _ID_post;
		
		private string _Post_title;
		
		private string _Post_content;
		
		private System.Nullable<System.DateTime> _Post_date;
		
		private System.Nullable<int> _ID_cat;
		
		private string _Post_thumb;
		
		public Post_SelectRandomResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_post", DbType="Int NOT NULL")]
		public int ID_post
		{
			get
			{
				return this._ID_post;
			}
			set
			{
				if ((this._ID_post != value))
				{
					this._ID_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_title", DbType="NVarChar(200)")]
		public string Post_title
		{
			get
			{
				return this._Post_title;
			}
			set
			{
				if ((this._Post_title != value))
				{
					this._Post_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_content", DbType="NVarChar(MAX)")]
		public string Post_content
		{
			get
			{
				return this._Post_content;
			}
			set
			{
				if ((this._Post_content != value))
				{
					this._Post_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Post_date
		{
			get
			{
				return this._Post_date;
			}
			set
			{
				if ((this._Post_date != value))
				{
					this._Post_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int")]
		public System.Nullable<int> ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this._ID_cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_thumb", DbType="NVarChar(100)")]
		public string Post_thumb
		{
			get
			{
				return this._Post_thumb;
			}
			set
			{
				if ((this._Post_thumb != value))
				{
					this._Post_thumb = value;
				}
			}
		}
	}
	
	public partial class Post_slideResult
	{
		
		private int _ID_post;
		
		private string _Post_title;
		
		private string _Post_content;
		
		private System.Nullable<System.DateTime> _Post_date;
		
		private System.Nullable<int> _ID_cat;
		
		private string _Post_thumb;
		
		public Post_slideResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_post", DbType="Int NOT NULL")]
		public int ID_post
		{
			get
			{
				return this._ID_post;
			}
			set
			{
				if ((this._ID_post != value))
				{
					this._ID_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_title", DbType="NVarChar(200)")]
		public string Post_title
		{
			get
			{
				return this._Post_title;
			}
			set
			{
				if ((this._Post_title != value))
				{
					this._Post_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_content", DbType="NVarChar(MAX)")]
		public string Post_content
		{
			get
			{
				return this._Post_content;
			}
			set
			{
				if ((this._Post_content != value))
				{
					this._Post_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Post_date
		{
			get
			{
				return this._Post_date;
			}
			set
			{
				if ((this._Post_date != value))
				{
					this._Post_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int")]
		public System.Nullable<int> ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this._ID_cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_thumb", DbType="NVarChar(100)")]
		public string Post_thumb
		{
			get
			{
				return this._Post_thumb;
			}
			set
			{
				if ((this._Post_thumb != value))
				{
					this._Post_thumb = value;
				}
			}
		}
	}
	
	public partial class User_SearchResult
	{
		
		private int _ID_user;
		
		private string _User_name;
		
		private string _User_pass;
		
		public User_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int NOT NULL")]
		public int ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					this._ID_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string User_name
		{
			get
			{
				return this._User_name;
			}
			set
			{
				if ((this._User_name != value))
				{
					this._User_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_pass", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string User_pass
		{
			get
			{
				return this._User_pass;
			}
			set
			{
				if ((this._User_pass != value))
				{
					this._User_pass = value;
				}
			}
		}
	}
	
	public partial class User_SelectAllResult
	{
		
		private int _ID_user;
		
		private string _User_name;
		
		private string _User_pass;
		
		public User_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int NOT NULL")]
		public int ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					this._ID_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string User_name
		{
			get
			{
				return this._User_name;
			}
			set
			{
				if ((this._User_name != value))
				{
					this._User_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_pass", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string User_pass
		{
			get
			{
				return this._User_pass;
			}
			set
			{
				if ((this._User_pass != value))
				{
					this._User_pass = value;
				}
			}
		}
	}
	
	public partial class Post_SelectAdminResult
	{
		
		private int _ID_post;
		
		private string _Post_title;
		
		private string _Post_content;
		
		private System.Nullable<System.DateTime> _Post_date;
		
		private System.Nullable<int> _ID_cat;
		
		private string _Post_thumb;
		
		private int _ID_cat1;
		
		private string _Cat_name;
		
		public Post_SelectAdminResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_post", DbType="Int NOT NULL")]
		public int ID_post
		{
			get
			{
				return this._ID_post;
			}
			set
			{
				if ((this._ID_post != value))
				{
					this._ID_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_title", DbType="NVarChar(200)")]
		public string Post_title
		{
			get
			{
				return this._Post_title;
			}
			set
			{
				if ((this._Post_title != value))
				{
					this._Post_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_content", DbType="NVarChar(MAX)")]
		public string Post_content
		{
			get
			{
				return this._Post_content;
			}
			set
			{
				if ((this._Post_content != value))
				{
					this._Post_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Post_date
		{
			get
			{
				return this._Post_date;
			}
			set
			{
				if ((this._Post_date != value))
				{
					this._Post_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int")]
		public System.Nullable<int> ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this._ID_cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_thumb", DbType="NVarChar(100)")]
		public string Post_thumb
		{
			get
			{
				return this._Post_thumb;
			}
			set
			{
				if ((this._Post_thumb != value))
				{
					this._Post_thumb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat1", DbType="Int NOT NULL")]
		public int ID_cat1
		{
			get
			{
				return this._ID_cat1;
			}
			set
			{
				if ((this._ID_cat1 != value))
				{
					this._ID_cat1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Cat_name
		{
			get
			{
				return this._Cat_name;
			}
			set
			{
				if ((this._Cat_name != value))
				{
					this._Cat_name = value;
				}
			}
		}
	}
	
	public partial class Post_SelectIDResult
	{
		
		private int _ID_post;
		
		private string _Post_title;
		
		private string _Post_content;
		
		private System.Nullable<System.DateTime> _Post_date;
		
		private System.Nullable<int> _ID_cat;
		
		private string _Post_thumb;
		
		private int _ID_cat1;
		
		private string _Cat_name;
		
		public Post_SelectIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_post", DbType="Int NOT NULL")]
		public int ID_post
		{
			get
			{
				return this._ID_post;
			}
			set
			{
				if ((this._ID_post != value))
				{
					this._ID_post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_title", DbType="NVarChar(200)")]
		public string Post_title
		{
			get
			{
				return this._Post_title;
			}
			set
			{
				if ((this._Post_title != value))
				{
					this._Post_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_content", DbType="NVarChar(MAX)")]
		public string Post_content
		{
			get
			{
				return this._Post_content;
			}
			set
			{
				if ((this._Post_content != value))
				{
					this._Post_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Post_date
		{
			get
			{
				return this._Post_date;
			}
			set
			{
				if ((this._Post_date != value))
				{
					this._Post_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat", DbType="Int")]
		public System.Nullable<int> ID_cat
		{
			get
			{
				return this._ID_cat;
			}
			set
			{
				if ((this._ID_cat != value))
				{
					this._ID_cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_thumb", DbType="NVarChar(100)")]
		public string Post_thumb
		{
			get
			{
				return this._Post_thumb;
			}
			set
			{
				if ((this._Post_thumb != value))
				{
					this._Post_thumb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cat1", DbType="Int NOT NULL")]
		public int ID_cat1
		{
			get
			{
				return this._ID_cat1;
			}
			set
			{
				if ((this._ID_cat1 != value))
				{
					this._ID_cat1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Cat_name
		{
			get
			{
				return this._Cat_name;
			}
			set
			{
				if ((this._Cat_name != value))
				{
					this._Cat_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
